[package]
name = "icc-patternfly-yew-table"
version = "0.1.0"
authors = ["Patrick Luell <pluell@iccdesigns.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
yew = "0.20"
yewtil = "0.4.0"